# Generated by Django 5.2.4 on 2025-08-13 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('area', 'Área'), ('unidade', 'Unidade'), ('topico', 'Tópico'), ('subtopico', 'Subtópico'), ('categoria', 'Categoria')], max_length=20)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subconteudos', to='app.conteudo')),
            ],
        ),
    ]
