# Generated by Django 5.2.4 on 2025-08-13 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subconteudos', to='app.conteudo'),
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('banca', models.CharField(max_length=100)),
                ('tipo_questao', models.CharField(max_length=50)),
                ('dificuldade', models.CharField(max_length=20)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='q_area', to='app.conteudo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='q_categoria', to='app.conteudo')),
                ('subtopico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='q_subtopico', to='app.conteudo')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='q_topico', to='app.conteudo')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='q_unidade', to='app.conteudo')),
            ],
        ),
    ]
