# Generated by Django 5.2.4 on 2025-08-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_conteudo_pai_questao'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='enunciado',
            field=models.TextField(default=''),
        ),
    ]
