# Generated by Django 5.2.4 on 2025-08-13 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_questao_enunciado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='q_categoria', to='app.conteudo'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='subtopico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='q_subtopico', to='app.conteudo'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='topico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='q_topico', to='app.conteudo'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='q_unidade', to='app.conteudo'),
        ),
    ]
