# Generated by Django 5.2.4 on 2025-11-01 13:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_questao_categoria_alter_questao_subtopico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='resposta',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questao',
            name='enunciado',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
