# Generated by Django 5.2.4 on 2025-11-01 13:41

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_questao_resposta_alter_questao_enunciado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='enunciado',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Enunciado'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='resposta',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Resposta'),
        ),
    ]
