# Generated by Django 5.2.4 on 2025-11-01 13:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_questao_resposta_alter_questao_enunciado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='enunciado',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Enunciado'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='resposta',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Resposta'),
        ),
    ]
