# Generated by Django 5.2.4 on 2025-11-01 19:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_questao_enunciado_alter_questao_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='resposta',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Resposta'),
        ),
    ]
