# Generated by Django 5.2.4 on 2025-11-03 17:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_questao_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='enunciado',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Enunciado'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='resposta',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Resposta'),
        ),
    ]
