# Generated by Django 5.2.4 on 2025-11-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_questao_enunciado_alter_questao_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='grau_escolaridade',
            field=models.CharField(choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('superior', 'Ensino Superior')], default='medio', max_length=20),
        ),
        migrations.AddField(
            model_name='questao',
            name='resposta_gabarito',
            field=models.CharField(blank=True, help_text='Ex: a) 1, b) 2, c) 3', max_length=50, null=True, verbose_name='Resposta do Gabarito'),
        ),
    ]
