# Generated by Django 5.2.4 on 2025-11-14 20:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_questao_grau_escolaridade_questao_resposta_gabarito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='resposta_gabarito',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Resposta do Gabarito'),
        ),
    ]
