# Generated by Django 5.2.4 on 2025-12-02 14:48

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_questao_resposta_gabarito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='nome',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='questao',
            name='grau_escolaridade',
            field=models.CharField(choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('superior', 'Ensino Superior')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questao',
            name='resposta_gabarito',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Resposta Gabarito'),
        ),
    ]
